### ISSUE TITLE
Need some way to separate log output by deploy

### ISSUE THREAD

**Issue by twof** [qutheory/red-feedback#10] opened 2019-03-12 00:57 UTC
URL: /apps/026C24E7-83B0-4745-8DB2-3800569C1EB0/commands/9292ED46-B488-4C0D-AF38-1F27895755DA
User ID: 7734849F-C5D2-454C-B00E-9564E95AD3C0
Company ID: 198CF095-A53C-4515-8DE0-264F8932D346

**Comment by joscdk** [comment] 2019-03-12 08:18
@twof not sure i fully follow this

**Comment by twof** [comment] 2019-03-12 19:28
Right now if you go to commands -> select the run command -> load logs

It shows all of the logs that have ever resulted from that command. If you've deployed a few dozen times, the file grows quite long.

Am I looking in the wrong place if I just want to follow the logs for my server?

**Comment by joscdk** [comment] 2019-03-12 19:31
Yeah it shows the full log for that particular command. However it should only show the last 200 lines. It will start a tail, so you should get updated logs automatically at the bottom.

We have plans of adding features to choose how many lines to show, and a way to clear the log files.

**Comment by joscdk** [comment] 2019-03-14 21:13
@twof so after putting some thought into this, the problem is we would need to make a new log file per deploy, which would just add a ton of files. So will close this for now, as we are building a "clear log" feature, that will allow you to clear the file.

**Closed as completed by joscdk** 2019-03-14 21:13 UTC
